### ISSUE TITLE
GHA上でビルドして、作成したイメージをECRに飛ばすworkflowを作成する

### ISSUE THREAD

**Issue by kaitokimuraofficial** [kaitokimuraofficial/onboarding_drs_infra#11]
# やりたいこと

| イメージ図 |
| -- |
| ![Image](https://github.com/user-attachments/assets/07702734-5c7e-44db-b1b4-8a1604ffae1a) |

# 作業
- [x] OpenID Connect (OIDC) プロバイダーを作成する
- [x] workflowのyamlを作成する
  - https://github.com/kaitokimuraofficial/daily_report_system/pull/75 

## OIDCプロバイダー
https://docs.github.com/ja/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

VPC エンドポイントは、プライベート IP アドレスを介して Amazon ECR APIs にプライベートにアクセスできるテクノロジーである AWS PrivateLink を利用しています。Fargate 起動タイプを使用する Amazon ECS タスクの場合、VPC エンドポイントを使用すると、タスクにパブリック IP アドレスを割り当てることなく、タスクは Amazon ECR からプライベートイメージをプルできます。

**Comment by kaitokimuraofficial** [comment]
# GHAのIAM Roleに付与する権限確認
https://github.com/aws-actions/amazon-ecr-login を使用してAWS ECRにログインする
このリポジトリのREADMEを確認すると
**プライベートなECRにログインするために必要**
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "GetAuthorizationToken",
      "Effect": "Allow",
      "Action": [
        "ecr:GetAuthorizationToken"
      ],
      "Resource": "*"
    }
  ]
}
```

GHAのworkflow内でプライベートなECRからpullするには、以下の権限が必要
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AllowPull",
      "Effect": "Allow",
      "Action": [
        "ecr:BatchGetImage",
        "ecr:GetDownloadUrlForLayer"
      ],
      "Resource": "arn:aws:ecr:us-east-1:123456789012:repository/my-ecr-repo"
    }
  ]
}
```

プライベートなECRにpushしたり、pullするには以下の権限が必要
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AllowPushPull",
      "Effect": "Allow",
      "Action": [
        "ecr:BatchGetImage",
        "ecr:BatchCheckLayerAvailability",
        "ecr:CompleteLayerUpload",
        "ecr:GetDownloadUrlForLayer",
        "ecr:InitiateLayerUpload",
        "ecr:PutImage",
        "ecr:UploadLayerPart"
      ],
      "Resource": "arn:aws:ecr:us-east-1:123456789012:repository/my-ecr-repo"
    }
  ]
}
```

**Comment by kaitokimuraofficial** [comment]
# Workflowのyaml
```yaml
name: Deploy to ECR

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

env:
  AWS_REGION: ap-northeast-1
  ROLE_TO_ASSUME: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/drs-deploy-github-actions"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Build-Deploy
    steps:
      - uses: Kesin11/actions-timeline@v2
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}

      - name: Login to AWS ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Compose
        run: |
          docker compose version

      - name: Build images with Docker Compose
        run: |
          docker compose build

      - name: Build, Tag, and Push Image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: main-drs-ap-northeast-1-dev
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          # Tag each image uniquely
          docker tag frontend:latest $REGISTRY/$REPOSITORY:frontend-$IMAGE_TAG
          docker tag backend:latest $REGISTRY/$REPOSITORY:backend-$IMAGE_TAG
          docker tag db:latest $REGISTRY/$REPOSITORY:db-$IMAGE_TAG

          # Push each tagged image
          docker push $REGISTRY/$REPOSITORY:frontend-$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:backend-$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:db-$IMAGE_TAG
```

**Comment by kaitokimuraofficial** [comment]
https://github.com/kaitokimuraofficial/daily_report_system/pull/75 で完了
close

**Comment by kaitokimuraofficial** [comment]
```yaml
name: Deploy to ECR

on:
  workflow_dispatch:
    branches:
      - deploy

permissions:
  contents: write
  id-token: write

env:
  AWS_REGION: ap-northeast-1
  ROLE_TO_ASSUME: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/drs-deploy-github-actions"

jobs:
  build-push:
    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest
    name: Build-Push
    steps:
      - uses: Kesin11/actions-timeline@v2
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}

      - name: Login to AWS ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: main-drs-ap-northeast-1-dev
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Tag each image uniquely
          
          docker build -t $REGISTRY/$REPOSITORY:frontend-$IMAGE_TAG ./frontend
          docker build -t $REGISTRY/$REPOSITORY:backend-$IMAGE_TAG ./rails
          docker build -t $REGISTRY/$REPOSITORY:db-$IMAGE_TAG ./db

          # Push each tagged image
          docker push $REGISTRY/$REPOSITORY:frontend-$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:backend-$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:db-$IMAGE_TAG
```
